# Generated by Django 3.0.8 on 2020-10-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Record')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Song')),
            ],
        ),
    ]
