# Generated by Django 3.0.8 on 2020-10-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='artist',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
